<a href="https://colab.research.google.com/github/vikash0837/PyTorch/blob/master/Pytorch_Tutorial_1_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Learning Pytorch Tutorial basics**
[Source](https://pytorch.org/tutorials/beginner/blitz/tensor_tutorial.html#sphx-glr-beginner-blitz-tensor-tutorial-py)


# **What is pytorch**

What is tensor?

> Tensors are similar to NumPy’s ndarrays, with the addition being that Tensors can also be used on a GPU to accelerate computing.


In [0]:
# import pytorch
import torch

In [0]:
#Construct a 5x3 matrix, uninitialized:
x = torch.empty(5,3)
print(x)

tensor([[2.7094e-36, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 2.8026e-45],
        [0.0000e+00, 1.1210e-44, 0.0000e+00],
        [1.4013e-45, 0.0000e+00, 0.0000e+00]])


In [0]:
#Construct a randomly initialized matrix:
x = torch.rand(5,3)
print(x)

tensor([[0.9412, 0.4282, 0.5352],
        [0.3230, 0.5266, 0.1650],
        [0.4645, 0.9926, 0.8089],
        [0.1282, 0.6461, 0.1631],
        [0.6677, 0.2246, 0.4553]])


In [0]:
#Construct a matrix filled zeros and of dtype long:
x = torch.zeros(5,3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [0]:
#Construct a tensor directly from data:
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [0]:
#Create a tensor based on an existing tensor. These methods will reuse properties of the input tensor, e.g. dtype, unless new values are provided by user
x = x.new_ones(5,3, dtype=torch.long)
print(x)


tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])


In [0]:
x = torch.randn_like(x,dtype=torch.double)
print(x)

tensor([[ 0.3483, -0.1353,  0.2126],
        [ 0.1525,  1.0402,  0.1865],
        [ 0.0962,  1.5675,  0.3869],
        [ 0.3639,  0.3263,  2.2082],
        [-0.2193, -0.6444,  1.5020]], dtype=torch.float64)


In [0]:
# get size
print(x.size())

torch.Size([5, 3])


**`Note`**: torch.Size is in fact a tuple, so it supports all tuple operations.

In [0]:
y = torch.rand(5,3)
z = x + y
print('X=',x,'\n','Y=',y,'\n','Z=',z)

X= tensor([[ 0.3483, -0.1353,  0.2126],
        [ 0.1525,  1.0402,  0.1865],
        [ 0.0962,  1.5675,  0.3869],
        [ 0.3639,  0.3263,  2.2082],
        [-0.2193, -0.6444,  1.5020]], dtype=torch.float64) 
 Y= tensor([[0.3783, 0.2750, 0.9853],
        [0.1278, 0.6404, 0.8398],
        [0.9994, 0.9125, 0.9513],
        [0.6075, 0.9838, 0.0287],
        [0.9074, 0.2566, 0.8413]]) 
 Z= tensor([[ 0.7265,  0.1398,  1.1979],
        [ 0.2803,  1.6806,  1.0263],
        [ 1.0956,  2.4799,  1.3383],
        [ 0.9714,  1.3101,  2.2370],
        [ 0.6881, -0.3878,  2.3433]], dtype=torch.float64)


In [0]:
# Additional add syntax
print(torch.add(x,y))

tensor([[ 0.7265,  0.1398,  1.1979],
        [ 0.2803,  1.6806,  1.0263],
        [ 1.0956,  2.4799,  1.3383],
        [ 0.9714,  1.3101,  2.2370],
        [ 0.6881, -0.3878,  2.3433]], dtype=torch.float64)


In [0]:
# Addition: providing an output tensor as argument
 result = torch.empty(5,3) # Garbage value initialization


In [0]:
 torch.add(x,y,out = result)
 print(result)

tensor([[ 0.7265,  0.1398,  1.1979],
        [ 0.2803,  1.6806,  1.0263],
        [ 1.0956,  2.4799,  1.3383],
        [ 0.9714,  1.3101,  2.2370],
        [ 0.6881, -0.3878,  2.3433]])


In [0]:
# Addition: in-place
y.add_(x)
print(y)

tensor([[ 0.7265,  0.1398,  1.1979],
        [ 0.2803,  1.6806,  1.0263],
        [ 1.0956,  2.4799,  1.3383],
        [ 0.9714,  1.3101,  2.2370],
        [ 0.6881, -0.3878,  2.3433]])


**Note:** `Any operation that mutates a tensor in-place is post-fixed with an _. For example: x.copy_(y), x.t_(), will change x.`





In [0]:
# You can use standard NumPy-like indexing with all bells and whistles!
print(x[:, 1])

tensor([-0.1353,  1.0402,  1.5675,  0.3263, -0.6444], dtype=torch.float64)


In [0]:
# Resizing: If you want to resize/reshape tensor, you can use torch.view:
x = torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8) # the size -1 is inferred from other dimention
print("X size=:",x.size(),'\n','Y size=:',y.size(),'\n','Z size=:',z.size())

X size=: torch.Size([4, 4]) 
 Y size=: torch.Size([16]) 
 Z size=: torch.Size([2, 8])


In [0]:
# If you have a one element tensor, use .item() to get the value as a Python number
x = torch.rand(1)
print(x)
print(x.item())

tensor([0.3591])
0.3591499328613281


In [0]:
x = torch.rand(1,2)
print(x)
print(x[:,1])


tensor([[0.3805, 0.9254]])
tensor([0.9254])


# NumPy Bridge


> Converting a Torch Tensor to a NumPy array and vice versa is a breeze.

> The Torch Tensor and NumPy array will share their underlying memory locations (if the Torch Tensor is on CPU), and changing one will change the other.



In [0]:
# Converting a Torch Tensor to a NumPy Array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [0]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [0]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


**Converting NumPy Array to Torch Tensor**

In [0]:
# See how changing the np array won't changed the Torch Tensor automatically
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
print(a)
print(b)

[1. 1. 1. 1. 1.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [0]:
a = a + 1
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [0]:
np.add(a,1,out=a)
print(a)
print(b)

[3. 3. 3. 3. 3.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [0]:
a = np.ones(5)
b = torch.from_numpy(a)
a = np.add(a,1)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([1., 1., 1., 1., 1.], dtype=torch.float64)


In [0]:
# See how changing the np array changed the Torch Tensor automatically
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a,1,out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


 **Note**: `All the Tensors on the CPU except a CharTensor support converting to NumPy and back.`

# **CUDA Tensors**


> Tensors can be moved onto any device using the .to method.



In [0]:
# let us run this cell only if CUDA is available
# We will use ``torch.device`` objects to move tensors in and out of GPU
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA device object
    y = torch.ones_like(x, device=device)  # directly create a tensor on GPU
    x = x.to(device)                       # or just use strings ``.to("cuda")``
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` can also change dtype together!
else:
  print("Cuda is not available")

Cuda is not available
